DROP TABLE items IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE families IF EXISTS;
DROP SEQUENCE GLOBAL_SEQ IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100;

CREATE TABLE families (
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(110)             NOT NULL
);

CREATE TABLE items (
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(110)             NOT NULL,
  quantity         DOUBLE                  NOT NULL,
  description      VARCHAR(255)                    ,
  price            INTEGER                         ,
  closed           BOOLEAN DEFAULT FALSE   NOT NULL,
  createdate       TIMESTAMP DEFAULT now() NOT NULL,
  closedate        TIMESTAMP,
  family_id        INTEGER                 NOT NULL,
  FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE
);

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(110)            NOT NULL,
  email            VARCHAR(110)            NOT NULL,
  password         VARCHAR(110)            NOT NULL,
  enabled          BOOLEAN DEFAULT TRUE    NOT NULL,
  role             VARCHAR(110),
  family_id        INTEGER,
  FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX users_unique_email_idx ON USERS (email);