DROP TABLE items IF EXISTS;
DROP SEQUENCE ITEMS_SEQ IF EXISTS;

CREATE SEQUENCE ITEMS_SEQ AS INTEGER START WITH 100;

CREATE TABLE items (
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE ITEMS_SEQ PRIMARY KEY,
  name             VARCHAR(30)             NOT NULL,
  quantity         DOUBLE                  NOT NULL,
  description      VARCHAR(255)                    ,
  price            INTEGER                         ,
  closed           BOOLEAN DEFAULT FALSE   NOT NULL,
  createdate       TIMESTAMP DEFAULT now() NOT NULL,
  closedate        TIMESTAMP
);